## ------------------------- ITEMS ------------------------- ##

## TRINKETS
expanded.items.trinkets.luckycoin.name=lucky coin
expanded.items.trinkets.luckycoin.desc=Legends say this coin belonged to a miserly king who outsmarted fortune itself in a game of heads or tails. It seems to attract more gold to its wearer and expand their business opportunities.
expanded.items.trinkets.luckycoin.stats_desc=At its current level this trinket will increase the amount of gold you find in the dungeon in _%s%%_, and the probability of replacing a food ration with gold by _%s%%_. And also will increase the number of items available in the shops by _%d_.\n\nThis trinket costs a large amount of energy to upgrade.
expanded.items.trinkets.luckycoin.typical_stats_desc=Typically this trinket will increase the amount of gold you find in the dungeon in _%s%%_, and the probability of replacing a food ration with gold by _%s%%_. And also will increase the number of items available in the shops by _%d_.\n\nThis trinket costs a large amount of energy to upgrade.

expanded.items.goldenration.name=Golden ration of food
expanded.items.goldenration.desc=Nothing fancy here: dried mea...\nNo, wait. It is made of solid gold; Your teeth wouldn't withstand it.\nPerhaps someone is willing to pay a modest price for it.
expanded.items.goldenration.discover_hint=You can find this item with a specific trinket.

expanded.items.trinkets.woodenspoon.name=Wooden spoon
expanded.items.trinkets.woodenspoon.desc=Wood is rigid when worked by a master craftsman, but this spoon, despite its age, has retained its shape so perfectly it seems like magic. Whoever its owner was is no longer with us, but their culinary work still endures.
expanded.items.trinkets.woodenspoon.typical_stats_desc=Typically This trinket _changes all the food_ in the dungeon to be replaced by _variants that provide benefits_ when consumed.
expanded.items.trinkets.woodenspoon.stats_desc=At its current level this trinket _changes all the food_ in the dungeon to be replaced by _variants that provide %s benefits_ when consumed.
expanded.items.trinkets.woodenspoon.level_tiny=tiny
expanded.items.trinkets.woodenspoon.level_modest=modest
expanded.items.trinkets.woodenspoon.level_large=large
expanded.items.trinkets.woodenspoon.level_huge=huge
expanded.items.trinkets.woodenspoon.react=This item is reacting with your _wooden spoon_.
expanded.items.trinkets.woodenspoon.function=This item has the same functionalities as _%s_.
expanded.items.trinkets.woodenspoon.pie_placeholder_name=Who knows what you will get.


## WEAPONS
items.weapon.melee.morningstar.name=morning star
items.weapon.melee.morningstar.desc=A light weapon with a heavy head, capable of delivering contingent blows with the proper technique.
items.weapon.melee.morningstar.stats_desc=This weapon benefits more from excess strength.
items.weapon.melee.morningstar.excess_str=Because of your excess strength, you will deal _%s-%d bonus damage_ with this weapon.
items.weapon.melee.morningstar.ability_name=head strike
items.weapon.melee.morningstar.typical_ability_desc=The Duelist can perform a _head strike_ with a moarning star. This attack typically deals _%1$d-%2$d damage_ and is guaranteed to hit. If the attack surprised the enemy it _paralyzes for one turn_.
items.weapon.melee.morningstar.ability_desc=The Duelist can perform a _head strike_ with a moarning star. This attack deals _%1$d-%2$d damage_ and is guaranteed to hit. If the attack surprised the enemy it _paralyzes for one turn_.


## FOOD
expanded.items.food.bun.name=Bun
expanded.items.food.bun.desc=A soft bun filled with beef.
expanded.items.food.bun.spoon_buff=The soft skin of the bun make you feel protected, giving you _%d_ shielding.

expanded.items.food.honey.name=Honey
expanded.items.food.honey.desc=A jar full of delicious honey.
expanded.items.food.honey.spoon_buff=The sweetness of honey makes you feel live, restoring _%d_ health.

expanded.items.food.wheatbread.name=Wheat bread
expanded.items.food.wheatbread.desc=A loaf of white bread with a soft interior and a crunchy exterior.
expanded.items.food.wheatbread.spoon_buff=The energy you gain from all the grains makes your skin harder to penetrate, reducing the damage take from _%d_ attacks.

expanded.items.food.ryebread.name=Rye bread
expanded.items.food.ryebread.desc=A loaf of brown bread with an incredible aroma and a texture that is neither hard nor soft.
expanded.items.food.ryebread.spoon_buff=The excess fat grains provide absorbs up to _%d_ damage. This fat is easily burned by moving around

expanded.items.food.driedmeat.name=Dried meat
expanded.items.food.driedmeat.desc=A piece of meat that is quite difficult to chew but very nutritious.
expanded.items.food.driedmeat.spoon_buff=This light snack lifts your spirits, guaranteeing %d random positive effects.
expanded.items.food.driedmeat.spoon_buff_variant=This light snack lifts your spirits, guaranteeing _%d_ or _%d_ random positive effects.
expanded.items.food.driedmeat.inspier=You feel inspired!
expanded.items.food.driedmeat.energy=You feel energetic!
expanded.items.food.driedmeat.better=You feel better!
expanded.items.food.driedmeat.mindvis=You see everything!
expanded.items.food.driedmeat.refresh=Refreshing!

expanded.items.food.ribs.name=Ribs
expanded.items.food.ribs.desc=Soft pieces of meat attached to a very thick bone.
expanded.items.food.ribs.spoon_buff=The smell of such a tasty snack lifts your spirits, guaranteeing _%d_ random positive effects.
expanded.items.food.ribs.spoon_buff_variant=The smell of such a tasty snack lifts your spirits, guaranteeing _%d_ or _%d_ random positive effects.
expanded.items.food.ribs.inspier=You feel inspired!
expanded.items.food.ribs.energy=You feel energetic!
expanded.items.food.ribs.hard=You feel your skin harden!
expanded.items.food.ribs.invis=You see your hands turn invisible!
expanded.items.food.ribs.nature=You feel connected to the nature!

expanded.items.food.pasta.name=Pasta
expanded.items.food.pasta.desc=This highly nutritious dish was consumed only by the prison guards. Some rumors say that high-ranking officials contaminated the food with substances that made the guards stronger and more violent towards the prisoners.
expanded.items.food.pasta.spoon_buff=The rumors were true; the substance inside this dish disturbs the consumer, leading them to a state of frenzy that increases the damage of their next attack by _%1$s%%_.

expanded.items.food.gruel.name=Gruel
expanded.items.food.gruel.desc=This distinctive dish was the main course in all prisons. It's very nutritious, but it has an unpleasant smell and texture due to the indiscriminate mixing of ingredients.\nAnd if that weren't enough, some guards would sometimes add very strong spices to prolong the suffering of the most violent prisoners.
expanded.items.food.gruel.spoon_buff=The extreme spiciness drives into a state of ferocity that lasts for _%d_ attacks and increases its damage depending on the duration of the effect.

expanded.items.food.goldenberry.name=Golden berry
expanded.items.food.goldenberry.desc=Despite its distinctive golden hue, the golden berry is hard to spot, even for someone as sharp-eyed as the huntress.
expanded.items.food.goldenberry.spoon_buff=The incredible sweetness of the golden berry makes it irresistible, and capable of providing _%d_ armor to the consumer.

expanded.items.food.survivalration.name=Survival ration
expanded.items.food.survivalration.desc=This ration was left by a member of the Thieves Guild. You found it, but at what cost? Survival rations are the last hope of a thief. Abandoning them is a sign that whoever left them couldn't make it.
expanded.items.food.survivalration.spoon_buff=There is a note on the back of the can.\n\n"I have no hope left, but you can still escape. Use this ration with caution, as it will make you invisible upon consumption."\n\nInvisibility will last for _%d_ turns.

expanded.items.food.hunterssandwich.name=Hunter's sandwich
expanded.items.food.hunterssandwich.desc=This delicious sandwich was used by merchants and hunters to keep them full while traveling long distances.
expanded.items.food.hunterssandwich.spoon_buff=Besides being much more filling than any other meal, This meal will increase the damage you deal by _%d_ while you are well fed. And also will increase your max health by _%d_ permanently.
expanded.items.food.hunterssandwich.huntress_special_buff=As a huntress, you had this sandwich as your companion on all your travels around the world. This dish reminds you of home and the promise to leave here alive. _The hunter's sandwich fills the huntress with determination_.

expanded.items.food.tartedebry.name=Brie tart
expanded.items.food.tartedebry.desc=This sweet tart is irresistible to anyone, being one of the most popular desserts among royalty.
expanded.items.food.tartedebry.spoon_buff=Besides being much more filling than any other meal, This meal will reduce the damage you take by _%d_ while you are well fed. And also will increase your max health by _%d_ permanently.
expanded.items.food.tartedebry.cleric_special_buff=As a cleric who was part of the royal family, you had many opportunities to taste this luxurious dessert. This dessert reminds you of home and the promise of getting out of here alive. _The brie tart fills the cleric with determination_.

## ------------------------- BUFFS ------------------------- ##

expanded.actors.buffs.frenzy.name=Frenzy
expanded.actors.buffs.frenzy.desc=The mind craves blood, the body must obey.\n\nThe next _%d_ attacks will cause _%s%%_ more damage.

expanded.actors.buffs.ferocity.name=Ferocity
expanded.actors.buffs.ferocity.desc=The body is burning from the inside and there is only one way to calm it.\n\nEach attack causes _extra damage equal to the duration of the effect_ and reduces it by one.\n\nTurns remaining and extra damage: _%d_.

expanded.items.food.wheatbread$carbohydraterush.name=Carbohydrate rush
expanded.items.food.wheatbread$carbohydraterush.desc=The large amounts of carbohydrates you have consumed causes the accumulation of a layer of fat that protects the vital organs.\n\nThis fat reduces the damage you recive by _1_ for the next _%d_ attacks.\n\nIf you continue eating grains you could gain more fat.

expanded.items.food.ryebread$carbohydraterush.name=Carbohydrate rush
expanded.items.food.ryebread$carbohydraterush.desc=The large amounts of carbohydrates you have consumed causes the accumulation of a layer of fat that protects the vital organs.\n\nThis fat absorbs up to _%d_ damage but can be burned quickly simply by moving around.\n\nIf you continue eating grains you could gain more fat.

expanded.actors.buffs.soulpact.name=Soul pact
expanded.actors.buffs.soulpact.desc=You've made a deal with the Wanderer in exchange for goods.\n\nSoul pact reduces your maximum health by _%d_, but it can't reduce it below 1.\n\nThis decision will stay with you until the end.\nWas it worth it?

actors.buffs.wellfed.hunter_sandwich_desc=Pacto de alma
actors.buffs.wellfed.soulpact.tarte_de_bry_desc=Pactaste con el 
actors.buffs.wellfed.soulpact.combo_desc=Pactaste con el 

actors.buffs.wellfed.hunter_sandwich_desc=You feel quite satisfied and full.\n\nWhile well fed, your hunger will not increase, and you will heal an additional amount of health over time.\n\nAdditionally, the Hunter's Sandwich makes you feel stronger, causing _%d_ extra damage.\n\nTurns remaining: %d.
actors.buffs.wellfed.tarte_de_bry_desc=You feel quite satisfied and full.\n\nWhile well fed, your hunger will not increase, and you will heal an additional amount of health over time.\n\nAdditionally, the Brie Tart makes you feel more resilient, reducing damage taken by _%d_.\n\nTurns remaining: %d.
actors.buffs.wellfed.combo_desc=You feel quite satisfied and full.\n\nWhile well fed, your hunger will not increase, and you will heal an additional amount of health over time.\n\nAdditionally, the Brie Tart and the Hunter's Sandwich make you feel stronger and more resilient, increasing damage dealt by _%d_ and reducing damage taken by _%d_.\n\nTurns remaining: %d.

## ------------------------- GLYPHS ------------------------- ##

expanded.items.armor.glyphs.vitality.name=%s of vitality
expanded.items.armor.glyphs.vitality.desc=This glyph adheres to the wearer's body to improve their health by increasing their maximum health.

## ------------------------- NPC ------------------------- ##

expanded.actors.npc.wanderingimp.name=Wanderer
expanded.actors.npc.wanderingimp.desc=An Imp like creature with many jewelry pieces around his body. His lapis lazuli cotton clothes shows how rich he is. One does not become this rich without stepping everyone he encounters.
expanded.actors.npc.wanderingimp.interact=A not crazy human, not a easy find.\n\nWould you like to enjoy my wares? Oh no, I don't want your gold, I want something else,\nI want your soul >:)\nNot all of it, just a piece, or whatever you're willing to offer me. In exchange, you can keep some of my goods.\n\nI have to leave very soon, so don't leave this floor unless you're done here.
expanded.actors.npc.wanderingimp.yell=Come closer %s, maybe we can negotiate.
expanded.actors.npc.wanderingimp.discover_hint=You can find this character if you explore the floor thoroughly before descending.
expanded.windows.wndsoultradeitem.pact=Pact for %d Soul
journal.notes$landmark.wandering_imp=Wanderer

